// Build the desktop UI with the Babel compiler already shipped in dist/vendor.
// Run with: node ui/scripts/build-offline.mjs
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const uiRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const srcRoot = join(uiRoot, 'src');
const distRoot = join(uiRoot, 'dist');
const compiler = {};
vm.runInNewContext(
  await readFile(join(distRoot, 'vendor', 'babel.min.js'), 'utf8'),
  compiler,
  { filename: 'babel.min.js' },
);

const modules = new Map();
const toId = (file) => relative(srcRoot, file).split(sep).join('/');

async function resolveImport(from, specifier) {
  const base = resolve(dirname(from), specifier);
  for (const candidate of [base, `${base}.tsx`, `${base}.ts`, `${base}.js`, join(base, 'index.ts')]) {
    if (['.ts', '.tsx', '.js'].includes(extname(candidate))) {
      try {
        await readFile(candidate);
        return candidate;
      } catch {
        // Try the next extension.
      }
    }
  }
  throw new Error(`Cannot resolve ${specifier} from ${from}`);
}

async function addModule(file) {
  const id = toId(file);
  if (modules.has(id)) return;
  const source = await readFile(file, 'utf8');
  const dependencies = {};
  modules.set(id, null);
  for (const match of source.matchAll(/(?:from\s*|import\s*)['"]([^'"]+)['"]/g)) {
    const specifier = match[1];
    if (specifier.endsWith('.css')) {
      dependencies[specifier] = null;
    } else if (specifier.startsWith('.')) {
      const dependency = await resolveImport(file, specifier);
      dependencies[specifier] = toId(dependency);
      await addModule(dependency);
    } else if (!['react', 'react-dom/client'].includes(specifier)) {
      throw new Error(`Unsupported package ${specifier} in ${file}`);
    }
  }
  const { code } = compiler.Babel.transform(source, {
    filename: file,
    presets: ['typescript', 'react'],
    plugins: ['transform-modules-commonjs'],
    comments: false,
    compact: false,
  });
  modules.set(id, { code, dependencies });
}

await addModule(join(srcRoot, 'main.tsx'));
const factories = [...modules].map(([id, value]) =>
  `${JSON.stringify(id)}: function(module, exports, require) {\n${value.code}\n}`,
).join(',\n');
const dependencies = Object.fromEntries(
  [...modules].map(([id, value]) => [id, value.dependencies]),
);
const bundle = `// Generated by ui/scripts/build-offline.mjs. Edit ui/src instead.\n` +
  `(function () {\n'use strict';\n` +
  `const factories = {\n${factories}\n};\n` +
  `const dependencies = ${JSON.stringify(dependencies)};\n` +
  `const cache = Object.create(null);\n` +
  `function load(id) {\n` +
  `  if (cache[id]) return cache[id].exports;\n` +
  `  const module = { exports: {} };\n` +
  `  cache[id] = module;\n` +
  `  factories[id](module, module.exports, function (name) {\n` +
  `    if (name === 'react') return window.React;\n` +
  `    if (name === 'react-dom/client') return window.ReactDOM;\n` +
  `    const target = dependencies[id][name];\n` +
  `    if (target === null) return {};\n` +
  `    if (!target) throw new Error('Unknown UI module: ' + name);\n` +
  `    return load(target);\n` +
  `  });\n` +
  `  return module.exports;\n` +
  `}\nload('main.tsx');\n})();\n`;

await writeFile(join(distRoot, 'app.js'), bundle);
await writeFile(join(distRoot, 'app.css'), await readFile(join(srcRoot, 'styles', 'app.css')));
await writeFile(join(distRoot, 'index.html'), `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Warehouse Shelf Mapper</title>
    <link rel="stylesheet" href="app.css" />
    <script defer src="vendor/react.production.min.js"></script>
    <script defer src="vendor/react-dom.production.min.js"></script>
    <script defer src="app.js"></script>
  </head>
  <body><div id="root"></div></body>
</html>
`);
console.log(`Built ${modules.size} UI modules into dist/app.js`);
